### ISSUE TITLE
Animation does not display correctly if the size of LikeButtonView is less than 200dp

### ISSUE THREAD

**Issue by amilcar-andrade** [frogermcs/LikeAnimation#8]
If you change the size of the LikeButtonView to 48dp then you can see how the animation does not display correctly. I guess you will need to build all of the other views based on the size of the LikeButtonView in order to correctly animate in smaller areas. To reproduce this issue, just change the size of the LikeButtonView inside activity_main of your sample app.

**Comment by yerenutku** [comment]
Is there any solution for this issue?
Here is my solution: change sizes in view_like_button.xml its not working correctly but its okey for now =)

**Comment by fjoglar** [comment]
As @yerenutku said, change sizes of DotsView and CircleView in view_like_button.xml.
Then change also maxDotSize within onSizeChanged() in DotsView.java.

Try some values and check the result. It's working ok for me.
